name: LorinthsRpWarps
description: Adds configurable and discoverable warps for your players to create and use
version: 1.0.0
main: me.lorinth.rpwarps.LorinthsRpWarps
api-version: 1.13
commands:
  rpw:
    aliases: [rpwarp]